### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by nmarkus2**

### CODE REVIEW

**Comment by zssherman** [comment]
Approving tests to run

**Comment by zssherman** [comment]
@nmarkus2 Looks good, want me to merge it? Or you adding anything else to this PR?

**Comment by nmarkus2** [comment]
Sure! Sounds good, thanks!

**Comment by zssherman** [comment]
@nmarkus2 Actually just noticed, I saw that there is a copy, I would say add your fully ran notebook into the notebooks folder, think execution is turned off, @mgrover1  thoughts?

**Comment by nmarkus2** [comment]
Just added the fully run notebook

**Comment by mgrover1** [comment]
@nmarkus2 can you fix the link to the USDA site? I would use the abbreviated one:
https://www.ers.usda.gov/topics/farm-economy/land-use-land-value-tenure/

**Comment by nmarkus2** [comment]
@mgrover1 making a few more edits to the code, will include the updated link in the next PR

**Pull request closed without merging**
