### PR TITLE
ENH: Adding an initial file for the students to test out.

### PR DESCRIPTION
**Pull request by AdamTheisen**

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@jrobrien91 @mgrover1 how does this look for an initial notebook for the students to follow through?

**Review by mgrover1 — APPROVED** [review]
I like this a lot!

**Comment by AdamTheisen** [comment]
Great!  Just as a note, I'm not sure what workflows are running but this will require the students to get an ARM username and token for downloading data.  I think I missed a couple requirements so will add those in and push them soon.

**Comment by mgrover1** [comment]
Great! Yeah - we should be able to add the token/username to the secrets here, similar to ACT and other cookbooks.

**Comment by jrobrien91** [comment]
- one link to the USDA ERS land use is throwing a compile error, but I will merge and correct if the notebook fails.

**Pull request merged**
